#!/bin/sh

ps ax | grep -i 'org\.apache\.zookeeper\.server\.quorum\.QuorumPeerMain' | grep java | grep -v grep | awk '{print $1" "$(NF-1)}'
ps ax | grep -i 'kafka\.kafka' | grep java | grep -v grep | awk '{print $1" "$(NF-1)}'
ps ax | grep -i 'backtype\.storm\.daemon\.nimbus' | grep java | grep -v grep | awk '{print $1" "$NF}'
ps ax | grep -i 'backtype\.storm\.daemon\.supervisor' | grep java | grep -v grep | awk '{print $1" "$NF}'
ps ax | grep -i 'backtype\.storm\.ui\.core' | grep java | grep -v grep | awk '{print $1" "$NF}'
